#!/bin/sh
#
#  taxo - Query the taxonomy database
#  Copyright (C) 2017  Marco van Zwetselaar <io@zwets.it>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Home: http://github.com/zwets/taxo

# Lookup the scientific name for numeric TAXID
taxid_sciname() {
    taxo-db "SELECT name FROM Names JOIN NameClass USING (name_class_id)
             WHERE tax_id = $1 AND name_class_name = 'scientific name';"
}

# Args: $1=TAXID [$2=anything]; when $2 is present, recurse upward to print all ancestors
lookup_taxid() {
    local NODE_LINE="$(taxo-db "SELECT * FROM SciNamesView WHERE tax_id = $1;")"
    [ -n "$NODE_LINE" ] || return
    if [ $# -eq 2 ]; then    # recurse up to root first
        local PARENT="$(field 4 "$NODE_LINE")"
        [ $PARENT -eq 1 ] || lookup_taxid $PARENT $2
    fi
    printf "$PRINTFMT" "$1" "$(field 2 "$NODE_LINE")" "$(field 3 "$NODE_LINE")"
}

# Exit this script with an error message on stderr
err_exit() {
    echo "$(basename "$0"): $*" >&2
    exit 1
}

# Show usage information and exit
usage_exit() {
    echo "
Usage: $(basename $0) [OPTIONS] TAXID|NAME|- ... 

  Retrieve taxonomy information from a local copy of the taxonomy database.

  For each numeric TAXID lookup the taxon.  For each (non-numeric) NAME, find
  all taxons whose scientific name contains NAME.

  OPTIONS
   -e, --exact      Search for the exact NAME (default is match anywhere)
   -r, --regex      Search for the regular expression NAME (excludes -e)
   -a, --any-name   Search in all name classes (synonyms, misspellings, etc)
   -x, --extended   Output extended information for each match
   -c, --citations  Output citations for each match
   -h, --help       This information

  This tool uses at its backend the taxo-db tool.  See 'taxo-db --help'.

  Note that the --regex option requires the REGEXP extension to SQLite3.
  On Ubuntu this extension is in package sqlite3-pcre.
" >&2
    exit ${1:-1}
}

# Parse options

unset OPT_E OPT_R OPT_A OPT_X OPT_C
while [ $# -ne 0 -a "$(expr "$1" : '\(.\)..*')" = "-" ]; do
    case $1 in
    -e|--exact)
        OPT_E=1
        ;;
    -r|--regexp)
        OPT_R=1
        ;;
    -a|--any-name)
        OPT_A=1
        ;;
    -x|--extended)
        OPT_X=1
        ;;
    -c|--citations)
        OPT_C=1
        ;;
    -h|--help)
        usage_exit 0
        ;;
    *) usage_exit
        ;;
    esac
    shift
done

# Check arguments

[ $# -ne 0 ] || usage_exit

# Locate the taxo-db backend

TAXO_DB="$(which taxo-db 2>/dev/null)"
[ -n "$TAXO_DB" ] || TAXO_DB="$(dirname "$0")/taxo-db"
[ -x "$TAXO_DB" ] || err_exit "cannot find taxo-db"

# Parse arguments, piping them into taxo-db

if [ "$1" = "-" ]; then
    cat
else
    while [ $# -ne 0 ]; do
        echo "$1"
        shift
    done
fi | awk -b -O -v EXACT="${OPT_E:-0}" -v EXTENDED="${OPT_X:-0}" -v REGEXP="${OPT_R:-0}" -v CITATIONS="${OPT_C:-0}" -v ALL_NAMES="${OPT_A:-0}" -v TAXO_DB="$TAXO_DB" -e '
BEGIN {
    if (REGEXP) TAXO_DB = TAXO_DB " -r"
    FS="\t"
}
END {
    close(TAXO_DB)
}
function find_taxon(tax_id) {
    if (!EXTENDED) {
        sql = "SELECT tax_id, rank_name, " (ALL_NAMES ? "name, name_class_name" : "sci_name") (CITATIONS ? ", Citations.*" : "")
        sql = sql " FROM " (ALL_NAMES ? "All" : "Sci") "NamesView"
    }
    else {
        sql = "SELECT * FROM Nodes NATURAL JOIN Names NATURAL JOIN NameClass NATURAL JOIN Ranks "
    }
    if (CITATIONS) sql = sql " NATURAL JOIN NodesCitations NATURAL JOIN Citations "
    printf "%s WHERE tax_id = %d;\n", sql, tax_id | TAXO_DB

}
function search_name(comparator) {
    if (!EXTENDED) {
        sql = "SELECT tax_id, rank_name, " (ALL_NAMES ? "name, name_class_name" : "sci_name") (CITATIONS ? ", Citations.*" : "")
        sql = sql " FROM " (ALL_NAMES ? "All" : "Sci") "NamesView"
        if (CITATIONS) sql = sql " NATURAL JOIN NodesCitations NATURAL JOIN Citations "
        sql = sql " WHERE "
        sql = sql (ALL_NAMES ? "name" : "sci_name")
    }
    else {
        sql = "SELECT * FROM Names NATURAL JOIN NameClass "
        if (CITATIONS) sql = sql " NATURAL JOIN NodesCitations NATURAL JOIN Citations "
        sql = sql " WHERE "
        if (!ALL_NAMES) sql = sql " name_class_name = \"scientific name\" AND "
        sql = sql " name "
    }
    printf "%s %s ORDER BY tax_id;\n", sql, comparator | TAXO_DB
}
/^ *[0-9]+$/   { find_taxon($0) }
/^ *[^0-9]/    { search_name(REGEXP ? " REGEXP \"" $0 "\"" : EXACT ? " = \"" $0 "\"" : " LIKE \"%" $0 "%\"") }
'

# vim: sts=4:sw=4:ai:si:et
